# Finds libajantv2, AJA's MIT-licensed NTV2 SDK.
#
#   git clone https://github.com/aja-video/libajantv2
#   cmake -S libajantv2 -B build && cmake --build build
#   ... then -DNTV2_DIR=/path/to/libajantv2 -DNTV2_BUILD_DIR=/path/to/build
#
# Unlike DeckLink and NDI this one is a static link, because that is how the
# SDK is meant to be consumed and its licence permits it. The consequence is
# that the AJA backend cannot be soft-failed at run time the way NDI is: a
# build either has it or does not.
#
# Sets: NTV2_FOUND, NTV2_INCLUDE_DIRS, NTV2_LIBRARIES

set(_ntv2_hints "${NTV2_DIR}" "$ENV{NTV2_DIR}")

find_path(NTV2_INCLUDE_DIR
  NAMES ajantv2/includes/ntv2card.h
  HINTS ${_ntv2_hints}
  PATH_SUFFIXES "" libajantv2
  DOC "Root of the libajantv2 source tree"
)

find_library(NTV2_LIBRARY
  NAMES ajantv2 ajantv2d
  HINTS "${NTV2_BUILD_DIR}" "$ENV{NTV2_BUILD_DIR}" ${_ntv2_hints}
  PATH_SUFFIXES lib build/lib ajalibraries
  DOC "The compiled ajantv2 static library"
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NTV2
  REQUIRED_VARS NTV2_INCLUDE_DIR NTV2_LIBRARY
  FAIL_MESSAGE "libajantv2 not found. Pass -DNTV2_DIR and -DNTV2_BUILD_DIR."
)

if(NTV2_FOUND)
  # The repo root must come first: ajabase/system/process.h and
  # ajantv2/includes/... are both included by path relative to it.
  set(NTV2_INCLUDE_DIRS
    "${NTV2_INCLUDE_DIR}"
    "${NTV2_INCLUDE_DIR}/ajantv2/includes"
  )

  # ntv2card.h pulls in the platform driver interface, which lives outside the
  # public includes directory.
  if(APPLE)
    list(APPEND NTV2_INCLUDE_DIRS "${NTV2_INCLUDE_DIR}/ajantv2/src/mac")
  elseif(WIN32)
    list(APPEND NTV2_INCLUDE_DIRS "${NTV2_INCLUDE_DIR}/ajantv2/src/win")
  else()
    list(APPEND NTV2_INCLUDE_DIRS "${NTV2_INCLUDE_DIR}/ajantv2/src/lin")
  endif()

  # ntv2version.h is generated by the SDK's own CMake run from
  # ntv2version.h.in, so it lives in the build tree, not the source tree.
  find_path(NTV2_GENERATED_INCLUDE_DIR
    NAMES ntv2version.h
    HINTS "${NTV2_BUILD_DIR}" "$ENV{NTV2_BUILD_DIR}"
    PATH_SUFFIXES ajantv2 includes ajantv2/includes
    NO_DEFAULT_PATH)
  if(NTV2_GENERATED_INCLUDE_DIR)
    list(APPEND NTV2_INCLUDE_DIRS "${NTV2_GENERATED_INCLUDE_DIR}")
  else()
    message(WARNING "libajantv2: generated ntv2version.h not found under "
                    "NTV2_BUILD_DIR — build the SDK first, or expect a "
                    "'ntv2version.h file not found' error.")
  endif()

  set(NTV2_LIBRARIES "${NTV2_LIBRARY}")
  if(APPLE)
    find_library(_ntv2_iokit IOKit REQUIRED)
    find_library(_ntv2_cf CoreFoundation REQUIRED)
    list(APPEND NTV2_LIBRARIES ${_ntv2_iokit} ${_ntv2_cf})
  endif()
endif()

mark_as_advanced(NTV2_INCLUDE_DIR NTV2_LIBRARY NTV2_GENERATED_INCLUDE_DIR)
